#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="timmins")]
public partial class TimminsDBDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Inserttbl_jobposting(tbl_jobposting instance);
  partial void Updatetbl_jobposting(tbl_jobposting instance);
  partial void Deletetbl_jobposting(tbl_jobposting instance);
  partial void Inserttbl_visitor(tbl_visitor instance);
  partial void Updatetbl_visitor(tbl_visitor instance);
  partial void Deletetbl_visitor(tbl_visitor instance);
  partial void Inserttbl_application(tbl_application instance);
  partial void Updatetbl_application(tbl_application instance);
  partial void Deletetbl_application(tbl_application instance);
  partial void Inserttbl_careeralert(tbl_careeralert instance);
  partial void Updatetbl_careeralert(tbl_careeralert instance);
  partial void Deletetbl_careeralert(tbl_careeralert instance);
  #endregion
	
	public TimminsDBDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["timminsConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public TimminsDBDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public TimminsDBDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public TimminsDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public TimminsDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tbl_jobposting> tbl_jobpostings
	{
		get
		{
			return this.GetTable<tbl_jobposting>();
		}
	}
	
	public System.Data.Linq.Table<tbl_visitor> tbl_visitors
	{
		get
		{
			return this.GetTable<tbl_visitor>();
		}
	}
	
	public System.Data.Linq.Table<tbl_application> tbl_applications
	{
		get
		{
			return this.GetTable<tbl_application>();
		}
	}
	
	public System.Data.Linq.Table<tbl_careeralert> tbl_careeralerts
	{
		get
		{
			return this.GetTable<tbl_careeralert>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="timmins.careeralertInsert")]
	public int careeralertInsert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string parName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string parDepartment, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string parEmail, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string parResume, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string parStatus)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parName, parDepartment, parEmail, parResume, parStatus);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="timmins.careeralert")]
	public ISingleResult<careeralertResult> careeralert()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<careeralertResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="timmins.careeralertByID")]
	public ISingleResult<careeralertByIDResult> careeralertByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> parID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parID);
		return ((ISingleResult<careeralertByIDResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="timmins.careeralertDelete")]
	public int careeralertDelete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> parID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parID);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="timmins.careeralertChangeStatus")]
	public int careeralertChangeStatus([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> parID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string parStatus)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parID, parStatus);
		return ((int)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="timmins.tbl_jobpostings")]
public partial class tbl_jobposting : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _jobposting_id;
	
	private string _title;
	
	private System.DateTime _date_posted;
	
	private string _hours;
	
	private string _department;
	
	private string _description;
	
	private string _qualifications;
	
	private string _salary;
	
	private System.DateTime _deadline;
	
	private EntitySet<tbl_application> _tbl_applications;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onjobposting_idChanging(int value);
    partial void Onjobposting_idChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void Ondate_postedChanging(System.DateTime value);
    partial void Ondate_postedChanged();
    partial void OnhoursChanging(string value);
    partial void OnhoursChanged();
    partial void OndepartmentChanging(string value);
    partial void OndepartmentChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnqualificationsChanging(string value);
    partial void OnqualificationsChanged();
    partial void OnsalaryChanging(string value);
    partial void OnsalaryChanged();
    partial void OndeadlineChanging(System.DateTime value);
    partial void OndeadlineChanged();
    #endregion
	
	public tbl_jobposting()
	{
		this._tbl_applications = new EntitySet<tbl_application>(new Action<tbl_application>(this.attach_tbl_applications), new Action<tbl_application>(this.detach_tbl_applications));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobposting_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int jobposting_id
	{
		get
		{
			return this._jobposting_id;
		}
		set
		{
			if ((this._jobposting_id != value))
			{
				this.Onjobposting_idChanging(value);
				this.SendPropertyChanging();
				this._jobposting_id = value;
				this.SendPropertyChanged("jobposting_id");
				this.Onjobposting_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string title
	{
		get
		{
			return this._title;
		}
		set
		{
			if ((this._title != value))
			{
				this.OntitleChanging(value);
				this.SendPropertyChanging();
				this._title = value;
				this.SendPropertyChanged("title");
				this.OntitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_posted", DbType="Date NOT NULL")]
	public System.DateTime date_posted
	{
		get
		{
			return this._date_posted;
		}
		set
		{
			if ((this._date_posted != value))
			{
				this.Ondate_postedChanging(value);
				this.SendPropertyChanging();
				this._date_posted = value;
				this.SendPropertyChanged("date_posted");
				this.Ondate_postedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hours", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string hours
	{
		get
		{
			return this._hours;
		}
		set
		{
			if ((this._hours != value))
			{
				this.OnhoursChanging(value);
				this.SendPropertyChanging();
				this._hours = value;
				this.SendPropertyChanged("hours");
				this.OnhoursChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string department
	{
		get
		{
			return this._department;
		}
		set
		{
			if ((this._department != value))
			{
				this.OndepartmentChanging(value);
				this.SendPropertyChanging();
				this._department = value;
				this.SendPropertyChanged("department");
				this.OndepartmentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this.OndescriptionChanging(value);
				this.SendPropertyChanging();
				this._description = value;
				this.SendPropertyChanged("description");
				this.OndescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qualifications", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string qualifications
	{
		get
		{
			return this._qualifications;
		}
		set
		{
			if ((this._qualifications != value))
			{
				this.OnqualificationsChanging(value);
				this.SendPropertyChanging();
				this._qualifications = value;
				this.SendPropertyChanged("qualifications");
				this.OnqualificationsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salary", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string salary
	{
		get
		{
			return this._salary;
		}
		set
		{
			if ((this._salary != value))
			{
				this.OnsalaryChanging(value);
				this.SendPropertyChanging();
				this._salary = value;
				this.SendPropertyChanged("salary");
				this.OnsalaryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deadline", DbType="Date NOT NULL")]
	public System.DateTime deadline
	{
		get
		{
			return this._deadline;
		}
		set
		{
			if ((this._deadline != value))
			{
				this.OndeadlineChanging(value);
				this.SendPropertyChanging();
				this._deadline = value;
				this.SendPropertyChanged("deadline");
				this.OndeadlineChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_jobposting_tbl_application", Storage="_tbl_applications", ThisKey="jobposting_id", OtherKey="jobposting_id")]
	public EntitySet<tbl_application> tbl_applications
	{
		get
		{
			return this._tbl_applications;
		}
		set
		{
			this._tbl_applications.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tbl_applications(tbl_application entity)
	{
		this.SendPropertyChanging();
		entity.tbl_jobposting = this;
	}
	
	private void detach_tbl_applications(tbl_application entity)
	{
		this.SendPropertyChanging();
		entity.tbl_jobposting = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="timmins.tbl_visitors")]
public partial class tbl_visitor : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _visitor_id;
	
	private string _name;
	
	private string _patient_name;
	
	private string _phone_number;
	
	private int _visitors;
	
	private System.DateTime _visit_date;
	
	private string _duration;
	
	private string _status;
	
	private string _email;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onvisitor_idChanging(int value);
    partial void Onvisitor_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onpatient_nameChanging(string value);
    partial void Onpatient_nameChanged();
    partial void Onphone_numberChanging(string value);
    partial void Onphone_numberChanged();
    partial void OnvisitorsChanging(int value);
    partial void OnvisitorsChanged();
    partial void Onvisit_dateChanging(System.DateTime value);
    partial void Onvisit_dateChanged();
    partial void OndurationChanging(string value);
    partial void OndurationChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
	
	public tbl_visitor()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visitor_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int visitor_id
	{
		get
		{
			return this._visitor_id;
		}
		set
		{
			if ((this._visitor_id != value))
			{
				this.Onvisitor_idChanging(value);
				this.SendPropertyChanging();
				this._visitor_id = value;
				this.SendPropertyChanged("visitor_id");
				this.Onvisitor_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_patient_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string patient_name
	{
		get
		{
			return this._patient_name;
		}
		set
		{
			if ((this._patient_name != value))
			{
				this.Onpatient_nameChanging(value);
				this.SendPropertyChanging();
				this._patient_name = value;
				this.SendPropertyChanged("patient_name");
				this.Onpatient_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_number", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string phone_number
	{
		get
		{
			return this._phone_number;
		}
		set
		{
			if ((this._phone_number != value))
			{
				this.Onphone_numberChanging(value);
				this.SendPropertyChanging();
				this._phone_number = value;
				this.SendPropertyChanged("phone_number");
				this.Onphone_numberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visitors", DbType="Int NOT NULL")]
	public int visitors
	{
		get
		{
			return this._visitors;
		}
		set
		{
			if ((this._visitors != value))
			{
				this.OnvisitorsChanging(value);
				this.SendPropertyChanging();
				this._visitors = value;
				this.SendPropertyChanged("visitors");
				this.OnvisitorsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit_date", DbType="Date NOT NULL")]
	public System.DateTime visit_date
	{
		get
		{
			return this._visit_date;
		}
		set
		{
			if ((this._visit_date != value))
			{
				this.Onvisit_dateChanging(value);
				this.SendPropertyChanging();
				this._visit_date = value;
				this.SendPropertyChanged("visit_date");
				this.Onvisit_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duration", DbType="VarChar(50)")]
	public string duration
	{
		get
		{
			return this._duration;
		}
		set
		{
			if ((this._duration != value))
			{
				this.OndurationChanging(value);
				this.SendPropertyChanging();
				this._duration = value;
				this.SendPropertyChanged("duration");
				this.OndurationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(50)")]
	public string status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="timmins.tbl_applications")]
public partial class tbl_application : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _application_id;
	
	private int _jobposting_id;
	
	private string _name;
	
	private string _email;
	
	private string _address;
	
	private string _city;
	
	private string _postalcode;
	
	private string _phonenumber;
	
	private string _resume;
	
	private string _coverletter;
	
	private System.DateTime _app_date;
	
	private EntityRef<tbl_jobposting> _tbl_jobposting;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onapplication_idChanging(int value);
    partial void Onapplication_idChanged();
    partial void Onjobposting_idChanging(int value);
    partial void Onjobposting_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnpostalcodeChanging(string value);
    partial void OnpostalcodeChanged();
    partial void OnphonenumberChanging(string value);
    partial void OnphonenumberChanged();
    partial void OnresumeChanging(string value);
    partial void OnresumeChanged();
    partial void OncoverletterChanging(string value);
    partial void OncoverletterChanged();
    partial void Onapp_dateChanging(System.DateTime value);
    partial void Onapp_dateChanged();
    #endregion
	
	public tbl_application()
	{
		this._tbl_jobposting = default(EntityRef<tbl_jobposting>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_application_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int application_id
	{
		get
		{
			return this._application_id;
		}
		set
		{
			if ((this._application_id != value))
			{
				this.Onapplication_idChanging(value);
				this.SendPropertyChanging();
				this._application_id = value;
				this.SendPropertyChanged("application_id");
				this.Onapplication_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobposting_id", DbType="Int NOT NULL")]
	public int jobposting_id
	{
		get
		{
			return this._jobposting_id;
		}
		set
		{
			if ((this._jobposting_id != value))
			{
				if (this._tbl_jobposting.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onjobposting_idChanging(value);
				this.SendPropertyChanging();
				this._jobposting_id = value;
				this.SendPropertyChanged("jobposting_id");
				this.Onjobposting_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(50)")]
	public string address
	{
		get
		{
			return this._address;
		}
		set
		{
			if ((this._address != value))
			{
				this.OnaddressChanging(value);
				this.SendPropertyChanging();
				this._address = value;
				this.SendPropertyChanged("address");
				this.OnaddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(50)")]
	public string city
	{
		get
		{
			return this._city;
		}
		set
		{
			if ((this._city != value))
			{
				this.OncityChanging(value);
				this.SendPropertyChanging();
				this._city = value;
				this.SendPropertyChanged("city");
				this.OncityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postalcode", DbType="VarChar(50)")]
	public string postalcode
	{
		get
		{
			return this._postalcode;
		}
		set
		{
			if ((this._postalcode != value))
			{
				this.OnpostalcodeChanging(value);
				this.SendPropertyChanging();
				this._postalcode = value;
				this.SendPropertyChanged("postalcode");
				this.OnpostalcodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phonenumber", DbType="VarChar(50)")]
	public string phonenumber
	{
		get
		{
			return this._phonenumber;
		}
		set
		{
			if ((this._phonenumber != value))
			{
				this.OnphonenumberChanging(value);
				this.SendPropertyChanging();
				this._phonenumber = value;
				this.SendPropertyChanged("phonenumber");
				this.OnphonenumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resume", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string resume
	{
		get
		{
			return this._resume;
		}
		set
		{
			if ((this._resume != value))
			{
				this.OnresumeChanging(value);
				this.SendPropertyChanging();
				this._resume = value;
				this.SendPropertyChanged("resume");
				this.OnresumeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coverletter", DbType="VarChar(50)")]
	public string coverletter
	{
		get
		{
			return this._coverletter;
		}
		set
		{
			if ((this._coverletter != value))
			{
				this.OncoverletterChanging(value);
				this.SendPropertyChanging();
				this._coverletter = value;
				this.SendPropertyChanged("coverletter");
				this.OncoverletterChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_app_date", DbType="Date NOT NULL")]
	public System.DateTime app_date
	{
		get
		{
			return this._app_date;
		}
		set
		{
			if ((this._app_date != value))
			{
				this.Onapp_dateChanging(value);
				this.SendPropertyChanging();
				this._app_date = value;
				this.SendPropertyChanged("app_date");
				this.Onapp_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_jobposting_tbl_application", Storage="_tbl_jobposting", ThisKey="jobposting_id", OtherKey="jobposting_id", IsForeignKey=true)]
	public tbl_jobposting tbl_jobposting
	{
		get
		{
			return this._tbl_jobposting.Entity;
		}
		set
		{
			tbl_jobposting previousValue = this._tbl_jobposting.Entity;
			if (((previousValue != value) 
						|| (this._tbl_jobposting.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tbl_jobposting.Entity = null;
					previousValue.tbl_applications.Remove(this);
				}
				this._tbl_jobposting.Entity = value;
				if ((value != null))
				{
					value.tbl_applications.Add(this);
					this._jobposting_id = value.jobposting_id;
				}
				else
				{
					this._jobposting_id = default(int);
				}
				this.SendPropertyChanged("tbl_jobposting");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="timmins.tbl_careeralert")]
public partial class tbl_careeralert : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _careeralert_id;
	
	private string _name;
	
	private string _department;
	
	private string _email;
	
	private string _resume;
	
	private string _status;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncareeralert_idChanging(int value);
    partial void Oncareeralert_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OndepartmentChanging(string value);
    partial void OndepartmentChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnresumeChanging(string value);
    partial void OnresumeChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
	
	public tbl_careeralert()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_careeralert_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int careeralert_id
	{
		get
		{
			return this._careeralert_id;
		}
		set
		{
			if ((this._careeralert_id != value))
			{
				this.Oncareeralert_idChanging(value);
				this.SendPropertyChanging();
				this._careeralert_id = value;
				this.SendPropertyChanged("careeralert_id");
				this.Oncareeralert_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string department
	{
		get
		{
			return this._department;
		}
		set
		{
			if ((this._department != value))
			{
				this.OndepartmentChanging(value);
				this.SendPropertyChanging();
				this._department = value;
				this.SendPropertyChanged("department");
				this.OndepartmentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resume", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string resume
	{
		get
		{
			return this._resume;
		}
		set
		{
			if ((this._resume != value))
			{
				this.OnresumeChanging(value);
				this.SendPropertyChanging();
				this._resume = value;
				this.SendPropertyChanged("resume");
				this.OnresumeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class careeralertResult
{
	
	private int _careeralert_id;
	
	private string _name;
	
	private string _department;
	
	private string _email;
	
	private string _resume;
	
	private string _status;
	
	public careeralertResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_careeralert_id", DbType="Int NOT NULL")]
	public int careeralert_id
	{
		get
		{
			return this._careeralert_id;
		}
		set
		{
			if ((this._careeralert_id != value))
			{
				this._careeralert_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this._name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string department
	{
		get
		{
			return this._department;
		}
		set
		{
			if ((this._department != value))
			{
				this._department = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this._email = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resume", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string resume
	{
		get
		{
			return this._resume;
		}
		set
		{
			if ((this._resume != value))
			{
				this._resume = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this._status = value;
			}
		}
	}
}

public partial class careeralertByIDResult
{
	
	private int _careeralert_id;
	
	private string _name;
	
	private string _department;
	
	private string _email;
	
	private string _resume;
	
	private string _status;
	
	public careeralertByIDResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_careeralert_id", DbType="Int NOT NULL")]
	public int careeralert_id
	{
		get
		{
			return this._careeralert_id;
		}
		set
		{
			if ((this._careeralert_id != value))
			{
				this._careeralert_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this._name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string department
	{
		get
		{
			return this._department;
		}
		set
		{
			if ((this._department != value))
			{
				this._department = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this._email = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resume", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string resume
	{
		get
		{
			return this._resume;
		}
		set
		{
			if ((this._resume != value))
			{
				this._resume = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this._status = value;
			}
		}
	}
}
#pragma warning restore 1591
